name: Go

on:
  [push, pull_request]
  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.7'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Format 
      run: cd src && go fmt ./...
        
    - name: Build
      run: cd src && go build -v ./...

    - name: Service Tests
      run: cd src && go test -v -p 1 ./... --tags=service
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}
    - name: Integration Tests
      run: cd src && go test -v -p 1 ./... --tags=integration
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}

