name: Go

on:
  [push, pull_request]
  

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Format 
      run: cd src && go fmt ./...
        
    - name: Build
      run: cd src && go build -v ./...

    - name: Test Graphing
      run: cd src && go test -v github.com/steamFriendsGraphing/graphing
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}

    - name: Test Server
      run: cd src && go test -v github.com/steamFriendsGraphing/server
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}

    - name: Test Worker
      run: cd src && go test -v github.com/steamFriendsGraphing/worker
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}

    - name: Test Worker
      run: cd src && go test -v github.com/steamFriendsGraphing/util
      env:
        APIKEY: ${{ secrets.APIKEY }}
        APIKEY1: ${{ secrets.APIKEY1 }}
        GITHUBACTIONS: ${{ secrets.GITHUBACTIONS }}

